import React, { useEffect, useState } from 'react';
import { useVisibility } from '../../../hooks/useVisibility';
import { useResolvedUniversalStyle } from '../../../hooks/useResolvedUniversalStyle';
import type { WidgetProps } from '../../types/index';
import { applyUniversalStyles } from '../../utils/styleBuilder';
import { useMaControl, useMaPlayerId } from './maSource';

type BrowseItem={uri:string;name:string;mediaType:string;provider:string;artwork?:string};
const MaBrowseWidget:React.FC<WidgetProps>=({config,isEditMode})=>{const cfg=config.config??{};const [path,setPath]=useState('');const [items,setItems]=useState<BrowseItem[]>([]);const [error,setError]=useState('');const visible=useVisibility(cfg.visibilityCondition);const style=useResolvedUniversalStyle(config.config.style);const mediaType=cfg.mediaType==='youtube_music'?'youtube_music':'music_assistant';const playerId=useMaPlayerId(cfg.playerId,10000);const control=useMaControl(playerId,mediaType);useEffect(()=>{let cancel=false;fetch(`/api/ma/browse?path=${encodeURIComponent(path)}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);if(!cancel){setItems(d.items||[]);setError('');}}).catch(e=>!cancel&&setError(String(e.message||e)));return()=>{cancel=true};},[path]);if(!visible)return null;const rowHeight=Math.max(28,Number(cfg.rowHeight??52)),iconSize=Math.max(16,Number(cfg.iconSize??36)),fontSize=Math.max(8,Number(cfg.fontSize??12));const open=(item:BrowseItem)=>{if(isEditMode)return;const folder=['folder','artist','album'].includes(item.mediaType);if(folder)setPath(item.uri);else void control.play(item.uri);};return <div style={applyUniversalStyles(style,{width:config.position?.width??cfg.width??330,height:config.position?.height??cfg.height??340,backgroundColor:cfg.backgroundColor??'#12161f',color:cfg.textColor??'#e6edf3',borderRadius:cfg.borderRadius??12,padding:12,boxSizing:'border-box',display:'flex',flexDirection:'column',gap:8,overflow:'hidden'})}><div style={{display:'flex',gap:8,alignItems:'center'}}>{path&&<button onClick={()=>setPath('')} style={{background:'transparent',border:0,color:'inherit'}}>←</button>}<strong>{cfg.title||'Browse Music'}</strong></div><div style={{overflowY:'auto',display:'flex',flexDirection:'column',gap:4}}>{items.slice(0,Math.max(1,Number(cfg.maxItems??100))).map(item=><button key={item.uri} disabled={isEditMode} onClick={()=>open(item)} style={{minHeight:rowHeight,background:'rgba(255,255,255,.06)',border:0,borderRadius:6,color:'inherit',display:'flex',alignItems:'center',gap:8,padding:'4px 8px',fontSize,textAlign:'left'}}>{item.artwork?<img src={item.artwork} alt="" style={{width:iconSize,height:iconSize,objectFit:'cover',borderRadius:4}}/>:<span>{['folder','artist','album'].includes(item.mediaType)?'▣':'♪'}</span>}<span style={{flex:1,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{item.name}<small style={{display:'block',opacity:.5}}>{item.mediaType}{item.provider?` · ${item.provider}`:''}</small></span></button>)}</div>{error&&<small style={{color:'#f85149'}}>{error}</small>}</div>};
export default MaBrowseWidget;
