import React, { useEffect, useState } from 'react';
import type { WidgetProps } from '../../types/index';
import { targetDeviceId } from './mediaSource';

interface YouTubeResult { id: string; name: string; channel: string; artwork: string; url: string }
const TOKEN = (import.meta.env as { VITE_CORE_AUTOMATION_TOKEN?: string }).VITE_CORE_AUTOMATION_TOKEN;
const headers = (): Record<string, string> => ({ 'Content-Type': 'application/json', ...(TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {}) });
const shell = (cfg: Record<string, any>, width: number, height: number): React.CSSProperties => ({ width, height, boxSizing: 'border-box', padding: 12, overflow: 'hidden', display: 'flex', flexDirection: 'column', gap: 8, borderRadius: cfg.borderRadius ?? 12, background: cfg.backgroundColor ?? '#12161f', color: cfg.textColor ?? '#e6edf3' });

async function play(value: string, title?: string) {
  const controllerDeviceId = targetDeviceId();
  return fetch('/api/youtube/play', { method: 'POST', credentials: 'include', headers: headers(), body: JSON.stringify({ value, title, ...(controllerDeviceId ? { controllerDeviceId } : {}) }) });
}
async function control(action: string, extra: Record<string, unknown> = {}) {
  const controllerDeviceId = targetDeviceId();
  return fetch('/api/media/control', { method: 'POST', credentials: 'include', headers: headers(), body: JSON.stringify({ action, source: 'youtube', ...(controllerDeviceId ? { controllerDeviceId } : {}), ...extra }) });
}

export const YouTubeSearch: React.FC<WidgetProps> = ({ config, isEditMode }) => {
  const cfg = config.config ?? {}; const width = config.position?.width ?? cfg.width ?? 360; const height = config.position?.height ?? cfg.height ?? 360;
  const [query, setQuery] = useState(''); const [results, setResults] = useState<YouTubeResult[]>([]); const [page, setPage] = useState(0); const [error, setError] = useState('');
  const pageSize = Math.max(1, Number(cfg.pageSize ?? 8)); const rowHeight = Math.max(40, Number(cfg.rowHeight ?? 72)); const iconSize = Math.max(28, Number(cfg.iconSize ?? 64)); const fontSize = Math.max(8, Number(cfg.fontSize ?? 13));
  const search = async () => { setError(''); setPage(0); const r = await fetch(`/api/youtube/search?q=${encodeURIComponent(query)}&limit=${Math.max(pageSize, Number(cfg.resultLimit ?? 25))}`); const d = await r.json(); if (!r.ok) setError(d.error || `HTTP ${r.status}`); else setResults(d.results || []); };
  const shown = results.slice(page * pageSize, (page + 1) * pageSize);
  return <div style={shell(cfg, width, height)}><form style={{ display: 'flex', gap: 6 }} onSubmit={e => { e.preventDefault(); if (!isEditMode && query.trim()) void search(); }}><input disabled={isEditMode} value={query} onChange={e => setQuery(e.target.value)} placeholder={cfg.placeholder || 'Search YouTube…'} style={{ flex: 1, minWidth: 0, padding: 8, border: 0, borderRadius: 6, background: 'rgba(255,255,255,.08)', color: 'inherit' }} /><button disabled={isEditMode || !query.trim()} style={{ background: cfg.accentColor ?? '#ff0033', color: '#fff', border: 0, borderRadius: 6, padding: '6px 14px' }}>Search</button></form><div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 5 }}>{shown.map(item => <button key={item.id} disabled={isEditMode} onClick={() => void play(item.url, item.name)} style={{ minHeight: rowHeight, flex: '0 0 auto', display: 'flex', gap: 10, alignItems: 'center', textAlign: 'left', background: 'rgba(255,255,255,.06)', color: 'inherit', border: 0, borderRadius: 7, padding: 6, fontSize }}><img src={item.artwork} alt="" style={{ width: iconSize, height: iconSize * .5625, objectFit: 'cover', borderRadius: 4 }} /><span style={{ minWidth: 0, flex: 1 }}><strong style={{ display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{item.name}</strong><small style={{ opacity: .55 }}>{item.channel}</small></span></button>)}</div>{error && <small style={{ color: '#f85149' }}>{error}</small>}<div style={{ display: 'flex', justifyContent: 'space-between' }}><button disabled={page === 0} onClick={() => setPage(p => p - 1)}>Previous</button><small>{results.length ? `${page + 1} / ${Math.ceil(results.length / pageSize)}` : 'No results'}</small><button disabled={(page + 1) * pageSize >= results.length} onClick={() => setPage(p => p + 1)}>Next</button></div></div>;
};

export const YouTubeSinglePlay: React.FC<WidgetProps> = ({ config, isEditMode }) => { const cfg = config.config ?? {}; return <button disabled={isEditMode || !cfg.value} onClick={() => void play(String(cfg.value), String(cfg.label || cfg.value))} style={{ ...shell(cfg, config.position?.width ?? cfg.width ?? 240, config.position?.height ?? cfg.height ?? 76), alignItems: 'center', justifyContent: 'center', border: `1px solid ${cfg.accentColor ?? '#ff0033'}`, fontSize: Number(cfg.fontSize ?? 15), fontWeight: 700 }}>▶ {cfg.label || 'Play YouTube'}</button>; };

export const YouTubePresets: React.FC<WidgetProps> = ({ config, isEditMode }) => { const cfg = config.config ?? {}; const items = String(cfg.items ?? '').split('\n').map((line: string) => { const [label, ...value] = line.split('|'); return { label: label.trim(), value: (value.join('|') || label).trim() }; }).filter((x: {value:string}) => x.value); return <div style={{ ...shell(cfg, config.position?.width ?? cfg.width ?? 360, config.position?.height ?? cfg.height ?? 180), display: 'grid', gridTemplateColumns: `repeat(${Math.max(1, Number(cfg.columns ?? 3))},1fr)`, overflowY: 'auto' }}>{items.map((item: {label:string;value:string}) => <button disabled={isEditMode} key={item.value} onClick={() => void play(item.value, item.label)} style={{ minHeight: Number(cfg.rowHeight ?? 56), background: 'rgba(255,255,255,.07)', color: 'inherit', border: 0, borderRadius: 7, fontSize: Number(cfg.fontSize ?? 13) }}>▶ {item.label}</button>)}</div>; };

export const YouTubeNowPlaying: React.FC<WidgetProps> = ({ config }) => { const cfg = config.config ?? {}; const [audio, setAudio] = useState<any>({}); useEffect(() => { const load = () => fetch('/api/media/state').then(r => r.json()).then(d => setAudio(d.audio || {})).catch(() => {}); load(); const id = window.setInterval(load, 3000); return () => clearInterval(id); }, []); return <div style={{ ...shell(cfg, config.position?.width ?? cfg.width ?? 360, config.position?.height ?? cfg.height ?? 110), flexDirection: 'row', alignItems: 'center' }}><span style={{ fontSize: 34, color: cfg.accentColor ?? '#ff0033' }}>▶</span><span><strong>{audio.source === 'youtube' ? audio.title : cfg.emptyText || 'Nothing playing'}</strong><small style={{ display: 'block', opacity: .55 }}>YouTube · {audio.state || 'idle'}</small></span></div>; };

export const YouTubeControls: React.FC<WidgetProps> = ({ config, isEditMode }) => { const cfg = config.config ?? {}; const size = Number(cfg.buttonSize ?? 42); const button = (label: string, action: string) => <button disabled={isEditMode} onClick={() => void control(action)} style={{ width: size, height: size, borderRadius: '50%', border: 0, background: 'rgba(255,255,255,.09)', color: 'inherit' }}>{label}</button>; return <div style={{ ...shell(cfg, config.position?.width ?? cfg.width ?? 300, config.position?.height ?? cfg.height ?? 90), flexDirection: 'row', alignItems: 'center', justifyContent: 'center' }}>{button('⏮','previous')}{button('▶','resume')}{button('Ⅱ','pause')}{button('■','stop')}{button('⏭','next')}</div>; };

export const YouTubeVolume: React.FC<WidgetProps> = ({ config, isEditMode }) => { const cfg = config.config ?? {}; const [value, setValue] = useState(Number(cfg.initialVolume ?? 75)); return <div style={shell(cfg, config.position?.width ?? cfg.width ?? 300, config.position?.height ?? cfg.height ?? 76)}><label>{cfg.label || 'YouTube volume'} · {value}%</label><input disabled={isEditMode} type="range" min="0" max="100" value={value} onChange={e => { const next = Number(e.target.value); setValue(next); void control('volume', { level: next }); }} /></div>; };
