import { createHash } from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import { RoutineRepository, type RoutineDefinition } from './routines.js';

export type RoutineLearningMode = 'off'|'suggest'|'automatic_drafts';
export interface LearnedCall { tool:string; args:Record<string,unknown> }

export class RoutineLearningService {
  constructor(private readonly pool:Pool) {}
  async mode():Promise<RoutineLearningMode>{const row=await this.pool.query("SELECT value FROM settings WHERE key='routine_learning_mode'");const value=String(row.rows[0]?.value??'suggest');return ['off','suggest','automatic_drafts'].includes(value)?value as RoutineLearningMode:'suggest';}
  async setMode(mode:RoutineLearningMode){await this.pool.query("INSERT INTO settings(key,value) VALUES ('routine_learning_mode',$1) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",[mode]);return mode;}
  async record(transcript:string,calls:LearnedCall[],deviceId?:string){const mode=await this.mode();if(mode==='off'||!calls.length)return null;if(calls.some(call=>elevated(call.tool)))return null;const normalized=normalizePhrase(transcript);if(!normalized)return null;const plan=calls.map(call=>({tool:call.tool,args:sanitize(call.args)}));const signature=createHash('sha256').update(JSON.stringify({normalized,plan})).digest('hex');const result=await this.pool.query(`INSERT INTO routine_plan_learning(signature,normalized_phrase,plan,success_count,status,origin_devices,first_seen_at,last_seen_at)
      VALUES($1,$2,$3::jsonb,1,'observed',$4::jsonb,now(),now()) ON CONFLICT(signature) DO UPDATE SET success_count=routine_plan_learning.success_count+1,last_seen_at=now() RETURNING *`,[signature,normalized,JSON.stringify(plan),JSON.stringify(deviceId?[deviceId]:[])]);const row=result.rows[0];if(Number(row.success_count)>=3&&row.status==='observed'){if(mode==='automatic_drafts'&&plan.some(call=>!call.tool.startsWith('ha.'))){const created=await new RoutineRepository(this.pool).create(compiledDefinition(normalized,plan),'learned_plan');const drafted=await this.pool.query("UPDATE routine_plan_learning SET status='drafted',routine_id=$2 WHERE signature=$1 RETURNING *",[signature,created.id]);return drafted.rows[0];}const promoted=await this.pool.query("UPDATE routine_plan_learning SET status='suggested' WHERE signature=$1 RETURNING *",[signature]);return promoted.rows[0];}return row;}
  async list(){return(await this.pool.query("SELECT * FROM routine_plan_learning WHERE status<>'dismissed' ORDER BY CASE status WHEN 'suggested' THEN 0 ELSE 1 END,last_seen_at DESC LIMIT 100")).rows;}
  async dismiss(signature:string){return(await this.pool.query("UPDATE routine_plan_learning SET status='dismissed' WHERE signature=$1 RETURNING *",[signature])).rows[0]??null;}
  async compile(signature:string){const result=await this.pool.query("SELECT * FROM routine_plan_learning WHERE signature=$1 AND status='suggested'",[signature]);const row=result.rows[0];if(!row)return null;const plan=row.plan as LearnedCall[];if(!Array.isArray(plan)||!plan.length||plan.every(call=>call.tool.startsWith('ha.')))throw new Error('learned_plan_not_canvas_owned');const created=await new RoutineRepository(this.pool).create(compiledDefinition(String(row.normalized_phrase),plan),'learned_plan');const updated=await this.pool.query("UPDATE routine_plan_learning SET status='drafted',routine_id=$2 WHERE signature=$1 RETURNING *",[signature,created.id]);return updated.rows[0];}
}

type RequireAdmin=(opts?:{roles?:('admin'|'viewer')[];csrf?:boolean})=>(request:FastifyRequest,reply:FastifyReply)=>Promise<void>;
export function registerRoutineLearningRoutes(fastify:FastifyInstance,service:RoutineLearningService,requireAdmin:RequireAdmin){fastify.get('/api/admin/routine-learning',{preHandler:requireAdmin({roles:['admin','viewer'],csrf:false})},async()=>({mode:await service.mode(),plans:await service.list()}));fastify.put('/api/admin/routine-learning/mode',{preHandler:requireAdmin({roles:['admin']})},async(request,reply)=>{const mode=(request.body as {mode?:unknown}|undefined)?.mode;if(!['off','suggest','automatic_drafts'].includes(String(mode)))return reply.code(400).send({error:'invalid_learning_mode'});return{ok:true,mode:await service.setMode(mode as RoutineLearningMode)};});fastify.post('/api/admin/routine-learning/:signature/dismiss',{preHandler:requireAdmin({roles:['admin']})},async(request,reply)=>{const plan=await service.dismiss((request.params as {signature:string}).signature);return plan?{ok:true,plan}:reply.code(404).send({error:'learned_plan_not_found'});});fastify.post('/api/admin/routine-learning/:signature/create-draft',{preHandler:requireAdmin({roles:['admin']})},async(request,reply)=>{try{const plan=await service.compile((request.params as {signature:string}).signature);return plan?{ok:true,plan,routineId:plan.routine_id}:reply.code(404).send({error:'learned_plan_not_found'});}catch(error){return reply.code(409).send({error:error instanceof Error?error.message:String(error)});}});}

function normalizePhrase(value:string){return value.toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();}
function elevated(tool:string){return /lock|alarm|garage|delete|shell|script|camera/i.test(tool);}
function sanitize(value:Record<string,unknown>){const output:Record<string,unknown>={};for(const [key,item] of Object.entries(value)){if(/token|password|secret|credential|api.?key/i.test(key))continue;output[key]=typeof item==='string'&&item.length>500?'[long-value-omitted]':item;}return output;}
function compiledDefinition(phrase:string,plan:LearnedCall[]):RoutineDefinition{return{schemaVersion:1,name:`Learned: ${phrase}`.slice(0,120),description:`Automatically drafted after the same successful request was observed three times.`,owner:'canvas_core',triggers:[{type:'voice',phrases:[phrase]}],inputs:{},steps:plan.map((call,index)=>({id:`learned_${index+1}`,kind:'tool' as const,config:{tool:call.tool,args:call.args}})),result:{speech:'Done.'},limits:{timeoutMs:30000,maxSteps:Math.max(1,plan.length),maxRoutineDepth:3}};}
