[Service]
Environment=XDG_RUNTIME_DIR=/run/user/1000
Environment=WAYLAND_DISPLAY=wayland-0
ProtectHome=no
InaccessiblePaths=/home /root
ExecStartPre=-+/usr/bin/setfacl -m u:canvas-edge-agent:--x /run/user/1000
ExecStartPre=-+/usr/bin/setfacl -m u:canvas-edge-agent:rw /run/user/1000/wayland-0
