import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Chip, Divider, FormControl, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import DeleteForeverIcon from '@mui/icons-material/DeleteForever';
import PlayArrowIcon from '@mui/icons-material/PlayArrow';
import SaveIcon from '@mui/icons-material/Save';
import ScienceIcon from '@mui/icons-material/Science';
import { coreApi, type DeviceRow, type HaEntityCatalogueItem, type LearnedRoutinePlan, type LegacyPage, type RoutineDefinition, type RoutineExecution, type RoutineLearningMode, type RoutineOwner, type RoutinePlan, type RoutineRecord, type RoutineRevision, type RoutineStep, type SceneRecord } from '../api/client';

const TOOLS = ['ha.toggle','ha.set_value','media.play','media.pause','media.resume','media.stop','media.next','brightness.set','scene.activate','navigate.page','navigate.panel','query.status'];
const blank = (): RoutineDefinition => ({ schemaVersion:1,name:'New routine',description:'',owner:'canvas_core',triggers:[{type:'manual'}],inputs:{},steps:[],result:{},limits:{timeoutMs:30000,maxSteps:30,maxRoutineDepth:3} });
const step = (kind:RoutineStep['kind']):RoutineStep => ({id:`${kind}_${crypto.randomUUID().slice(0,8)}`,kind,config:kind==='tool'?{tool:'ha.toggle',args:{}}:kind==='delay'?{ms:1000}:kind==='condition'?{left:'',operator:'equals',right:''}:kind==='routine'?{routineId:''}:{} });

export default function RoutinesSettingsSection() {
  const [routines,setRoutines]=useState<RoutineRecord[]>([]); const [selected,setSelected]=useState<string>('new');
  const [definition,setDefinition]=useState<RoutineDefinition>(blank()); const [entities,setEntities]=useState<HaEntityCatalogueItem[]>([]);
  const [pages,setPages]=useState<LegacyPage[]>([]); const [scenes,setScenes]=useState<SceneRecord[]>([]); const [devices,setDevices]=useState<DeviceRow[]>([]);
  const [executions,setExecutions]=useState<RoutineExecution[]>([]); const [simulation,setSimulation]=useState<Record<string,unknown>|null>(null);
  const [revisions,setRevisions]=useState<RoutineRevision[]>([]);
  const [aiPrompt,setAiPrompt]=useState(''); const [aiPlan,setAiPlan]=useState<RoutinePlan|null>(null); const [aiResolutions,setAiResolutions]=useState<Record<string,string>>({});
  const [learningMode,setLearningMode]=useState<RoutineLearningMode>('suggest');const [learnedPlans,setLearnedPlans]=useState<LearnedRoutinePlan[]>([]);
  const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);

  const load=useCallback(async()=>{ const [rr,ha,pp,ss,dd]=await Promise.all([coreApi.routines(),coreApi.haEntities(),coreApi.pages(),coreApi.scenes(),coreApi.devices()]); setRoutines(rr.routines);setEntities(ha.entities);setPages(pp);setScenes(ss.scenes);setDevices(dd.devices); },[]);
  useEffect(()=>{void load().catch(e=>setError((e as Error).message));},[load]);
  useEffect(()=>{void coreApi.routineLearning().then(value=>{setLearningMode(value.mode);setLearnedPlans(value.plans);}).catch(e=>setError((e as Error).message));},[]);
  useEffect(()=>{ if(selected==='new'){setExecutions([]);setRevisions([]);return;} void Promise.all([coreApi.routine(selected),coreApi.routineExecutions(selected)]).then(([detail,history])=>{const rows=detail.routine.revisions??[];const revision=rows[0];if(revision)setDefinition(structuredClone(revision.definition));setRevisions(rows);setExecutions(history.executions);}).catch(e=>setError((e as Error).message));},[selected]);
  const selectedRecord=routines.find(r=>r.id===selected); const latestRevision=selectedRecord?.active_revision;
  const permissionTools=useMemo(()=>definition.steps.filter(s=>s.kind==='tool').map(s=>String(s.config.tool)),[definition.steps]);
  const updateStep=(index:number,next:RoutineStep)=>setDefinition(d=>({...d,steps:d.steps.map((s,i)=>i===index?next:s)}));

  async function act(operation:()=>Promise<void>){setBusy(true);setError(null);setMessage(null);try{await operation();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const save=()=>act(async()=>{const validation=await coreApi.validateRoutine(definition);if(!validation.valid)throw new Error(validation.errors.map(e=>`${e.path}: ${e.message}`).join('\n'));if(selected==='new'){const created=await coreApi.createRoutine(definition);setSelected(created.routine.id);setMessage('Draft created.');}else{await coreApi.reviseRoutine(selected,definition);setMessage('New immutable draft revision saved.');}});
  const simulate=()=>act(async()=>{if(selected==='new')throw new Error('Save the draft before simulation.');const result=await coreApi.simulateRoutine(selected);setSimulation(result.simulation);setMessage('Simulation completed without executing actions.');});
  const enable=()=>act(async()=>{if(selected==='new')throw new Error('Save the draft first.');await coreApi.enableRoutine(selected);setMessage('Latest validated revision enabled.');});
  const run=()=>act(async()=>{if(selected==='new')throw new Error('Save and enable the routine first.');const result=await coreApi.runRoutine(selected,devices[0]?.id);setMessage(`Execution ${result.execution.status}.`);setExecutions((await coreApi.routineExecutions(selected)).executions);});
  const planWithAi=()=>act(async()=>{setAiResolutions({});const result=await coreApi.planRoutine(aiPrompt,selected==='new'?undefined:selected);setAiPlan(result.plan);setMessage(selected==='new'?'AI plan created for review. Nothing was enabled.':'AI revision planned against the selected routine. Nothing was saved or enabled.');});
  const resolveAiTarget=(value:string,entityId:string)=>act(async()=>{const resolutions={...aiResolutions,[value]:entityId};setAiResolutions(resolutions);const result=await coreApi.planRoutine(aiPrompt,selected==='new'?undefined:selected,resolutions);setAiPlan(result.plan);setMessage(`Target “${value}” bound to ${entityId}. Review the updated plan.`);});
  const createAiDraft=()=>act(async()=>{if(!aiPlan?.definition)throw new Error('The plan has no valid definition.');const editing=selected==='new'?undefined:selected;const result=await coreApi.createPlannedRoutineDraft(aiPlan.definition,editing);setDefinition(structuredClone(aiPlan.definition));setSelected(result.routine.id);if(editing){const detail=await coreApi.routine(editing);setRevisions(detail.routine.revisions??[]);}setMessage(editing?'New immutable AI draft revision created. The enabled revision was not changed.':'AI routine draft created. Review and enable it explicitly when ready.');setAiPlan(null);setAiPrompt('');});

  return <Stack spacing={2}>
    {error&&<Alert severity="error" sx={{whiteSpace:'pre-wrap'}} onClose={()=>setError(null)}>{error}</Alert>}{message&&<Alert severity="success" onClose={()=>setMessage(null)}>{message}</Alert>}
    <Paper sx={{p:2}}><Typography variant="h6">{selected==='new'?'Create with AI':`Edit “${selectedRecord?.name??'routine'}” with AI`}</Typography><Typography variant="body2" color="text.secondary">{selected==='new'?'Describe the behavior. Canvas will resolve known targets, recommend where it belongs, and produce a disabled draft for review.':'Describe only the change you want. Canvas will preserve unrelated behavior and prepare a new immutable draft revision.'}</Typography><Stack direction={{xs:'column',md:'row'}} spacing={1} sx={{mt:1}}><TextField fullWidth size="small" label={selected==='new'?'What should the routine do?':'How should this routine change?'} placeholder={selected==='new'?'Turn off the lounge lights every weekday at 11 PM':'Also turn off the driveway light'} value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&aiPrompt.trim())void planWithAi();}}/><Button variant="contained" disabled={busy||!aiPrompt.trim()} startIcon={<ScienceIcon/>} onClick={planWithAi}>{selected==='new'?'Plan':'Plan revision'}</Button></Stack>
      {aiPlan&&<Paper variant="outlined" sx={{p:1.5,mt:1.5}}><Stack direction="row" spacing={1} sx={{alignItems:'center',flexWrap:'wrap'}}><Chip label={`Owner: ${aiPlan.owner.replace('_',' ')}`} color={aiPlan.owner==='clarification_required'?'warning':'primary'}/><Chip label={`Risk: ${aiPlan.risk}`} color={aiPlan.risk==='elevated'?'error':aiPlan.risk==='medium'?'warning':'success'}/>{aiPlan.permissions.map(value=><Chip size="small" key={value} label={value}/>)}</Stack><Typography variant="body2" sx={{mt:1}}>{aiPlan.expectedBehavior}</Typography>{aiPlan.changes.length>0&&<Box sx={{mt:1}}><Typography variant="subtitle2">Proposed changes</Typography>{aiPlan.changes.map(change=><Typography key={change.path} variant="caption" sx={{display:'block'}} color="text.secondary">• {change.path} will change</Typography>)}</Box>}{aiPlan.reasons.map(reason=><Typography key={reason} variant="caption" sx={{display:'block'}} color="text.secondary">• {reason}</Typography>)}{aiPlan.unresolved.map(value=><Alert key={value} severity="warning" sx={{mt:1}}><Stack direction={{xs:'column',sm:'row'}} spacing={1} sx={{alignItems:{sm:'center'}}}><Typography variant="body2">Choose the exact entity for “{value}”</Typography><FormControl size="small" sx={{minWidth:300}}><InputLabel>Home Assistant entity</InputLabel><Select label="Home Assistant entity" value="" onChange={e=>void resolveAiTarget(value,String(e.target.value))}>{entities.map(entity=><MenuItem key={entity.entity_id} value={entity.entity_id}>{entity.friendly_name||entity.entity_id} · {entity.entity_id}</MenuItem>)}</Select></FormControl></Stack></Alert>)}{aiPlan.ambiguous.map(value=><Alert key={value.value} severity="warning" sx={{mt:1}}><Typography variant="body2">Which entity did “{value.value}” mean?</Typography><Stack direction="row" spacing={1} sx={{mt:.5,flexWrap:'wrap'}}>{value.candidates.map(candidate=><Button key={candidate} size="small" variant="outlined" onClick={()=>void resolveAiTarget(value.value,candidate)}>{candidate}</Button>)}</Stack></Alert>)}{aiPlan.haDraft&&<Alert severity="info" sx={{mt:1}}>{aiPlan.haDraft.reason}</Alert>}{!aiPlan.validation.valid&&<Alert severity="error" sx={{mt:1}}>The generated plan is not schema-valid: {aiPlan.validation.errors.map(value=>`${value.path}: ${value.message}`).join('; ')}</Alert>}<Stack direction="row" spacing={1} sx={{mt:1.5}}><Button variant="outlined" disabled={!aiPlan.definition} onClick={()=>{if(aiPlan.definition){setDefinition(structuredClone(aiPlan.definition));if(selected==='new')setSelected('new');setMessage('Plan loaded into the visual builder for editing.');}}}>Edit in builder</Button><Button variant="contained" disabled={!aiPlan.definition||!aiPlan.validation.valid||aiPlan.owner==='home_assistant'||aiPlan.owner==='hybrid'||aiPlan.owner==='clarification_required'} onClick={createAiDraft}>{selected==='new'?'Create disabled draft':'Save draft revision'}</Button></Stack></Paper>}
    </Paper>
    <Paper sx={{p:2}}><Stack direction={{xs:'column',sm:'row'}} spacing={1} sx={{alignItems:{sm:'center'}}}><Box sx={{flex:1}}><Typography variant="h6">Repeated-request learning</Typography><Typography variant="body2" color="text.secondary">Only stable, successful and non-elevated tool plans become suggestions after three matching uses. Secrets and long values are not retained.</Typography></Box><FormControl size="small" sx={{minWidth:190}}><InputLabel>Learning mode</InputLabel><Select label="Learning mode" value={learningMode} onChange={e=>void act(async()=>{const mode=e.target.value as RoutineLearningMode;await coreApi.setRoutineLearningMode(mode);setLearningMode(mode);setMessage(`Routine learning set to ${mode.replace('_',' ')}.`);})}><MenuItem value="off">Off</MenuItem><MenuItem value="suggest">Suggest</MenuItem><MenuItem value="automatic_drafts">Automatic drafts</MenuItem></Select></FormControl></Stack>{learnedPlans.filter(plan=>['suggested','drafted'].includes(plan.status)).map(plan=><Paper key={plan.signature} variant="outlined" sx={{p:1.25,mt:1}}><Stack direction={{xs:'column',sm:'row'}} spacing={1} sx={{alignItems:{sm:'center'}}}><Box sx={{flex:1}}><Stack direction="row" spacing={.5}><Typography variant="subtitle2">“{plan.normalized_phrase}”</Typography><Chip size="small" label={plan.status}/></Stack><Typography variant="caption" color="text.secondary">Seen successfully {plan.success_count} times · {plan.plan.map(call=>call.tool).join(' → ')}{plan.fast_path_hits>0?` · ${plan.fast_path_hits} fast-path hits · last ${plan.last_fast_path_ms}ms`:''}</Typography></Box>{plan.status==='suggested'&&<Button size="small" variant="outlined" onClick={()=>void act(async()=>{const created=await coreApi.createLearnedRoutineDraft(plan.signature);await load();setLearnedPlans(plans=>plans.map(value=>value.signature===plan.signature?{...value,status:'drafted',routine_id:created.routineId}:value));setSelected(created.routineId);setMessage('Disabled learned draft created. Review it, then enable it to activate the guarded fast path.');})}>Create draft</Button>}<Button size="small" onClick={()=>void act(async()=>{await coreApi.dismissLearnedRoutinePlan(plan.signature);setLearnedPlans(plans=>plans.filter(value=>value.signature!==plan.signature));})}>Dismiss</Button></Stack></Paper>)}</Paper>
    <Stack direction={{xs:'column',md:'row'}} spacing={2} sx={{alignItems:'stretch'}}>
      <Paper sx={{p:2,width:{md:260},flexShrink:0}}>
        <Button fullWidth variant="contained" startIcon={<AddIcon/>} onClick={()=>{setDefinition(blank());setSelected('new');}} sx={{mb:1,textTransform:'none'}}>New routine</Button>
        <Stack spacing={1}>{routines.map(r=><Button key={r.id} variant={selected===r.id?'outlined':'text'} onClick={()=>setSelected(r.id)} sx={{justifyContent:'space-between',textTransform:'none'}}><span>{r.name}</span><Chip size="small" label={r.status}/></Button>)}</Stack>
      </Paper>
      <Paper sx={{p:2.5,flex:1,minWidth:0}}>
        <Stack direction="row" sx={{alignItems:'center'}} spacing={1}><Typography variant="h6">Routine builder</Typography>{selectedRecord&&<Chip size="small" label={`${selectedRecord.status}${latestRevision?` · r${latestRevision}`:''}`}/>}</Stack>
        <Typography variant="caption" color="text.secondary">Trigger → Conditions → Actions → Result. Saving an existing routine creates a new immutable draft revision.</Typography><Divider sx={{my:2}}/>
        {revisions.length>0&&<Stack direction="row" spacing={.5} sx={{mb:2,flexWrap:'wrap'}}>{revisions.map(r=><Chip key={r.id} size="small" variant={r.status==='enabled'?'filled':'outlined'} color={r.status==='enabled'?'success':'default'} label={`r${r.revision} · ${r.status} · ${r.creation_source}`}/>)}</Stack>}
        <Stack spacing={1.5}>
          <TextField size="small" label="Name" value={definition.name} onChange={e=>setDefinition({...definition,name:e.target.value})}/>
          <TextField size="small" label="Description" value={definition.description??''} onChange={e=>setDefinition({...definition,description:e.target.value})}/>
          <FormControl size="small"><InputLabel>Recommended owner</InputLabel><Select label="Recommended owner" value={definition.owner} onChange={e=>setDefinition({...definition,owner:e.target.value as RoutineOwner})}><MenuItem value="canvas_core">Canvas Core</MenuItem><MenuItem value="home_assistant">Home Assistant</MenuItem><MenuItem value="hybrid">Hybrid</MenuItem><MenuItem value="clarification_required">Clarification required</MenuItem></Select></FormControl>
          <TriggerEditor definition={definition} entities={entities} onChange={setDefinition}/>
          <Typography variant="subtitle2">Conditions and actions</Typography>
          {definition.steps.map((s,i)=><StepEditor key={s.id} value={s} entities={entities} pages={pages} scenes={scenes} routines={routines} onChange={n=>updateStep(i,n)} onDelete={()=>setDefinition(d=>({...d,steps:d.steps.filter((_,x)=>x!==i)}))}/>) }
          <Stack direction="row" spacing={1} sx={{flexWrap:'wrap'}}>{(['tool','condition','delay','routine','result'] as const).map(k=><Button key={k} size="small" variant="outlined" onClick={()=>setDefinition(d=>({...d,steps:[...d.steps,step(k)]}))}>+ {k}</Button>)}</Stack>
          <Divider/><Stack direction="row" spacing={1} sx={{flexWrap:'wrap'}}><Button disabled={busy} variant="contained" startIcon={<SaveIcon/>} onClick={save}>Save draft</Button><Button disabled={busy||selected==='new'} variant="outlined" startIcon={<ScienceIcon/>} onClick={simulate}>Simulate</Button><Button disabled={busy||selected==='new'} variant="outlined" onClick={enable}>Enable latest</Button><Button disabled={busy||selectedRecord?.status!=='enabled'} color="success" variant="outlined" startIcon={<PlayArrowIcon/>} onClick={run}>Run once</Button>{selectedRecord?.status==='enabled'&&<Button disabled={busy} color="warning" onClick={()=>act(async()=>{await coreApi.setRoutineStatus(selected,'disable');setMessage('Routine disabled.');})}>Disable</Button>}</Stack>
        </Stack>
      </Paper>
    </Stack>
    <Stack direction={{xs:'column',md:'row'}} spacing={2}>
      <Paper sx={{p:2,flex:1}}><Typography variant="subtitle2">Permission summary</Typography><Divider sx={{my:1}}/>{permissionTools.length?permissionTools.map(t=><Chip key={t} size="small" label={t} sx={{mr:.5,mb:.5}}/>):<Typography variant="body2" color="text.secondary">No tool permissions requested.</Typography>}</Paper>
      <Paper sx={{p:2,flex:1}}><Typography variant="subtitle2">Latest simulation</Typography><Divider sx={{my:1}}/><Box component="pre" sx={{fontSize:11,whiteSpace:'pre-wrap',maxHeight:220,overflow:'auto'}}>{simulation?JSON.stringify(simulation,null,2):'Save and simulate to inspect validation and confirmation requirements.'}</Box></Paper>
    </Stack>
    <Paper sx={{p:2}}><Typography variant="subtitle2">Execution history</Typography><Divider sx={{my:1}}/><Stack spacing={.75}>{executions.map(e=><Stack key={e.id} direction="row" spacing={1} sx={{alignItems:'center'}}><Chip size="small" color={e.status==='successful'?'success':e.status==='failed'?'error':'default'} label={e.status}/><Typography variant="body2">{new Date(e.started_at).toLocaleString()}</Typography><Typography variant="caption" color="text.secondary">{e.id}</Typography>{e.error&&<Typography variant="caption" color="error">{e.error}</Typography>}{e.status==='awaiting_confirmation'&&<Button size="small" color="warning" onClick={()=>act(async()=>{await coreApi.confirmRoutineExecution(e.id);setExecutions((await coreApi.routineExecutions(selected)).executions);setMessage('Confirmed execution completed.');})}>Confirm</Button>}{['running','awaiting_confirmation'].includes(e.status)&&<Button size="small" onClick={()=>act(async()=>{await coreApi.cancelRoutineExecution(e.id);setExecutions((await coreApi.routineExecutions(selected)).executions);})}>Cancel</Button>}</Stack>)}{!executions.length&&<Typography variant="body2" color="text.secondary">No executions recorded.</Typography>}</Stack></Paper>
  </Stack>;
}

function TriggerEditor({definition,entities,onChange}:{definition:RoutineDefinition;entities:HaEntityCatalogueItem[];onChange:(value:RoutineDefinition)=>void}) {
  const trigger=definition.triggers[0]??{type:'manual'};
  const replace=(next:Record<string,unknown>&{type:string})=>onChange({...definition,triggers:[next]});
  const type=String(trigger.type??'manual');
  const days=Array.isArray(trigger.days)?trigger.days.map(Number):[];
  return <Paper variant="outlined" sx={{p:1.5}}><Typography variant="subtitle2">Trigger</Typography>
    <Stack direction={{xs:'column',sm:'row'}} spacing={1} sx={{mt:1,flexWrap:'wrap'}}>
      <FormControl size="small" sx={{minWidth:160}}><InputLabel>Type</InputLabel><Select label="Type" value={type} onChange={e=>replace({type:e.target.value})}>{['manual','voice','schedule','mqtt','ha_event','webhook','canvas_button'].map(v=><MenuItem key={v} value={v}>{v.replace('_',' ')}</MenuItem>)}</Select></FormControl>
      {type==='voice'&&<TextField size="small" label="Voice phrases (comma separated)" fullWidth value={Array.isArray(trigger.phrases)?trigger.phrases.join(', '):''} onChange={e=>replace({type:'voice',phrases:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)})}/>} 
      {type==='schedule'&&<><TextField size="small" type="time" label="Local time" slotProps={{inputLabel:{shrink:true}}} value={String(trigger.time??'09:00')} onChange={e=>replace({...trigger,type:'schedule',time:e.target.value})}/><TextField size="small" label="IANA timezone" value={String(trigger.timezone??Intl.DateTimeFormat().resolvedOptions().timeZone)} onChange={e=>replace({...trigger,type:'schedule',timezone:e.target.value})}/><FormControl size="small" sx={{minWidth:220}}><InputLabel>Days (empty means every day)</InputLabel><Select multiple label="Days (empty means every day)" value={days} onChange={e=>replace({...trigger,type:'schedule',days:(e.target.value as number[])})}>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((label,index)=><MenuItem key={label} value={index}>{label}</MenuItem>)}</Select></FormControl></>}
      {type==='ha_event'&&<><FormControl size="small" sx={{minWidth:280}}><InputLabel>Home Assistant entity</InputLabel><Select label="Home Assistant entity" value={String(trigger.entityId??'')} onChange={e=>replace({...trigger,type:'ha_event',entityId:e.target.value})}>{entities.map(entity=><MenuItem key={entity.entity_id} value={entity.entity_id}>{entity.friendly_name||entity.entity_id} · {entity.state}</MenuItem>)}</Select></FormControl><TextField size="small" label="From state (optional)" value={String(trigger.from??'')} onChange={e=>replace({...trigger,type:'ha_event',from:e.target.value||undefined})}/><TextField size="small" label="To state (optional)" value={String(trigger.to??'')} onChange={e=>replace({...trigger,type:'ha_event',to:e.target.value||undefined})}/></>}
    </Stack>
    {type==='mqtt'&&<Typography variant="caption" color="text.secondary">Publish to canvas/routines/&lt;routine-id&gt;/trigger with a unique actionId and an ISO-8601 expiresAt time. Expired or duplicate commands will not execute.</Typography>}
    {type==='webhook'&&<Typography variant="caption" color="text.secondary">Use the authenticated POST endpoint shown by the API for this routine.</Typography>}
    {type==='canvas_button'&&<Typography variant="caption" color="text.secondary">Canvas buttons can invoke this routine by its routine ID.</Typography>}
  </Paper>;
}

function StepEditor({value,entities,pages,scenes,routines,onChange,onDelete}:{value:RoutineStep;entities:HaEntityCatalogueItem[];pages:LegacyPage[];scenes:SceneRecord[];routines:RoutineRecord[];onChange:(s:RoutineStep)=>void;onDelete:()=>void}) {
  const config=value.config; const tool=String(config.tool??'ha.toggle'); const args=(config.args??{}) as Record<string,unknown>;
  const setArgs=(next:Record<string,unknown>)=>onChange({...value,config:{...config,args:next}});
  return <Paper variant="outlined" sx={{p:1.5}}><Stack direction="row" spacing={1} sx={{alignItems:'center'}}><Chip size="small" label={value.kind}/><TextField size="small" label="Step ID" value={value.id} onChange={e=>onChange({...value,id:e.target.value})} sx={{width:180}}/><FormControl size="small" sx={{ml:'auto!important',minWidth:130}}><InputLabel>On failure</InputLabel><Select label="On failure" value={value.onFailure??'stop'} onChange={e=>onChange({...value,onFailure:e.target.value as 'stop'|'continue'})}><MenuItem value="stop">Stop</MenuItem><MenuItem value="continue">Continue</MenuItem></Select></FormControl><Button color="error" onClick={onDelete} startIcon={<DeleteForeverIcon/>}>Remove</Button></Stack>
    {value.kind==='tool'&&<Stack spacing={1} sx={{mt:1}}><FormControl size="small"><InputLabel>Tool</InputLabel><Select label="Tool" value={tool} onChange={e=>onChange({...value,config:{tool:e.target.value,args:{}}})}>{TOOLS.map(t=><MenuItem key={t} value={t}>{t}</MenuItem>)}</Select></FormControl>{tool.startsWith('ha.')&&<FormControl size="small"><InputLabel>Entity</InputLabel><Select label="Entity" value={String(args.entity_id??'')} onChange={e=>setArgs({...args,entity_id:e.target.value})}>{entities.map(e=><MenuItem key={e.entity_id} value={e.entity_id}>{e.friendly_name||e.entity_id} · {e.state}</MenuItem>)}</Select></FormControl>}{tool==='ha.toggle'&&<FormControl size="small"><InputLabel>State</InputLabel><Select label="State" value={String(args.state??'toggle')} onChange={e=>setArgs({...args,state:e.target.value})}><MenuItem value="on">On</MenuItem><MenuItem value="off">Off</MenuItem><MenuItem value="toggle">Toggle</MenuItem></Select></FormControl>}{tool==='navigate.page'&&<FormControl size="small"><InputLabel>Page</InputLabel><Select label="Page" value={String(args.page??'')} onChange={e=>setArgs({...args,page:e.target.value})}>{pages.map(p=><MenuItem key={p.id} value={p.id}>{p.name}</MenuItem>)}</Select></FormControl>}{tool==='scene.activate'&&<FormControl size="small"><InputLabel>Scene</InputLabel><Select label="Scene" value={String(args.scene??'')} onChange={e=>setArgs({...args,scene:e.target.value})}>{scenes.map(s=><MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>)}</Select></FormControl>}<TextField size="small" label="Arguments JSON" multiline value={JSON.stringify(args)} onChange={e=>{try{setArgs(JSON.parse(e.target.value));}catch{/* retain last valid value */}}}/></Stack>}
    {value.kind==='delay'&&<TextField sx={{mt:1}} size="small" type="number" label="Milliseconds" value={Number(config.ms??0)} onChange={e=>onChange({...value,config:{ms:Number(e.target.value)}})}/>} {value.kind==='condition'&&<Stack direction="row" spacing={1} sx={{mt:1}}><TextField size="small" label="Left" value={String(config.left??'')} onChange={e=>onChange({...value,config:{...config,left:e.target.value}})}/><Select size="small" value={String(config.operator??'equals')} onChange={e=>onChange({...value,config:{...config,operator:e.target.value}})}>{['equals','not_equals','greater_than','less_than','contains'].map(o=><MenuItem key={o} value={o}>{o}</MenuItem>)}</Select><TextField size="small" label="Right" value={String(config.right??'')} onChange={e=>onChange({...value,config:{...config,right:e.target.value}})}/></Stack>}{value.kind==='routine'&&<FormControl fullWidth size="small" sx={{mt:1}}><InputLabel>Child routine</InputLabel><Select label="Child routine" value={String(config.routineId??'')} onChange={e=>onChange({...value,config:{routineId:e.target.value}})}>{routines.filter(r=>r.status==='enabled').map(r=><MenuItem key={r.id} value={r.id}>{r.name}</MenuItem>)}</Select></FormControl>}{value.kind==='result'&&<TextField fullWidth size="small" sx={{mt:1}} label="Result message" value={String(config.message??'')} onChange={e=>onChange({...value,config:{message:e.target.value}})}/>}</Paper>;
}
